### ISSUE TITLE
Auto-restart of jobs if killed

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/cryoem-cloud-tools#134]
Related to 'cheapest' option - need automated way to restart jobs that stopped b/c instance was killed

**Comment by mcianfrocco** [comment]
Currently - if job runs through without issue, it does not terminate properly from the qsub_aws script.

**Comment by mcianfrocco** [comment]
Now job will complete successfully if no issues. Still working on restarting if instance terminates.

**Comment by mcianfrocco** [comment]
When trying to continue: 

Traceback (most recent call last):
  File "/Users/mcianfro/software/repo/spot/cryoem-cloud-tools/relion/qsub_aws_dev", line 4705, in <module>
    relion_refine_mpi(project,AZ_letter)
  File "/Users/mcianfro/software/repo/spot/cryoem-cloud-tools/relion/qsub_aws_dev", line 1398, in relion_refine_mpi
    relion_remote_cmd='mpirun -np %i /home/EM_Packages/relion2.0/build/bin/relion_refine_mpi --continue %s --o %s/run_ct%s --iter %s --tau2_fudge %s --particle_diameter %s --oversampling 1 --psi_step %s --offset_range %s --offset_step %s %s %s' %(mpi,optimiser,outdir,str(int(currentIteration)-1),str(numiters),tau,diam,psistep,offrange,offstep,j,gpu)
UnboundLocalError: local variable 'psistep' referenced before assignment

**Comment by mcianfrocco** [comment]
Works except for spot instance error: 


An error occurred (MaxSpotInstanceCountExceeded) when calling the RequestSpotInstances operation: Max spot instance count exceeded
Traceback (most recent call last):
  File "/Users/mcianfro/software/repo/cryoem-cloud-tools/cryoem-cloud-tools/aws//launch_AWS_instance.py", line 522, in <module>
    instanceID,PublicIP=launchInstance(params,keyName,keyPath,AMI,AWS_ACCOUNT_ID)
  File "/Users/mcianfro/software/repo/cryoem-cloud-tools/cryoem-cloud-tools/aws//launch_AWS_instance.py", line 321, in launchInstance
    SpotRequestOutputJson = json.loads(SpotRequestOutput)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/Users/mcianfro/software/repo/spot/cryoem-cloud-tools/relion/qsub_aws_dev", line 4693, in <module>
    relion_refine_mpi(project,AZ_letter)
  File "/Users/mcianfro/software/repo/spot/cryoem-cloud-tools/relion/qsub_aws_dev", line 1310, in relion_refine_mpi
    instanceID=subprocess.Popen('cat %s/awslog.log | grep ID' %(outdir), shell=True, stdout=subprocess.PIPE).stdout.read().split('ID:')[-1].strip().strip().split()[0]
IndexError: list index out of range

Need to double check that spot request is fully terminated before another spot request

Also - the 3D refine job tried to restart after it finished.

**Comment by mcianfrocco** [comment]
Works!
