### ISSUE TITLE
Fabric connection times out, kills submission

### ISSUE THREAD

**Issue by mcianfrocco** [leschzinerlab/cryoem-cloud-tools#83]
Sometimes fabric loses connection with an instance. 

Potential fix: 
http://linuxplayer.org/2014/03/some-fabric-trap-and-tricks

<pre>  File "/home/michaelc/Scripts/AWS//aws//launch_AWS_instance.py", line 402, in <module>
    AttachMountEBSVol(instanceID,params['volume'],PublicIP,keyPath)
  File "/home/michaelc/Scripts/AWS//aws//launch_AWS_instance.py", line 329, in AttachMountEBSVol
    dir_exists=exec_remote_cmd('ls /data')
  File "/home/michaelc/Scripts/AWS//aws//launch_AWS_instance.py", line 356, in exec_remote_cmd
    return run(cmd)
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 683, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/operations.py", line 1090, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/usr/lib/python2.7/site-packages/fabric/operations.py", line 930, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/lib/python2.7/site-packages/fabric/state.py", line 424, in default_channel
    chan = _open_session()
  File "/usr/lib/python2.7/site-packages/fabric/state.py", line 416, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 609, in connect
    raise NetworkError(msg, e)
fabric.exceptions.NetworkError: Timed out trying to connect to 52.37.118.71 (tried 1 time)
Traceback (most recent call last):
  File "/home/michaelc/Scripts/AWS//relion//qsub_aws_dev", line 3023, in <module>
    relion_refine_mpi(project)
  File "/home/michaelc/Scripts/AWS//relion//qsub_aws_dev", line 1066, in relion_refine_mpi
    exec_remote_cmd('mkdir /%s/%s' %(dirlocation,entry))
  File "/home/michaelc/Scripts/AWS//relion//qsub_aws_dev", line 397, in exec_remote_cmd
    return run(cmd)
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 683, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/operations.py", line 1090, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/usr/lib/python2.7/site-packages/fabric/operations.py", line 930, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/lib/python2.7/site-packages/fabric/state.py", line 424, in default_channel
    chan = _open_session()
  File "/usr/lib/python2.7/site-packages/fabric/state.py", line 416, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/lib/python2.7/site-packages/fabric/network.py", line 609, in connect
    raise NetworkError(msg, e)
fabric.exceptions.NetworkError: Timed out trying to connect to 52.37.118.71 (tried 1 time)</pre>

**Comment by mcianfrocco** [comment]
Turned out this issue was related to the way I was checking which security group a machine belonged to. Fixed.
